### ISSUE TITLE
ページ遷移・ローディングアニメーション実装

### ISSUE THREAD

**Issue by naoki-00-ito** [INxST/st-portfolio#104]
ページ遷移と最初のローディングに関して
@naoki-00-ito 

最初のローディングは最初に名前部分だけアニメーションつきで表示したい！[
このサイトのように](https://www.yukotakada-work.com/)名前の後に他の要素を表示させる感じです
他の要素が[このサイト](https://seitaroyamazaki.com/)のようにぼかしを使ってインする（ぼかしフェードインアウトはサイトを通して使っていきたい）

ページ遷移は、ぼかしフェードインのみで行いたいです

ページがローディングされた時に、文字が切り替わってガクッとなるのが微妙だからそれが見えないようにしたいなあ、
トップの部分無理そうであれば別のローディング検討します、、

_Originally posted by @taiki0521 in https://github.com/INxST/st-portfolio/issues/24#issuecomment-2291756213_

**Comment by naoki-00-ito** [comment]
@taiki0521 
オープニングアニメーションとページ遷移アニメーション追加してみたのでご確認お願いします！
https://inxst.github.io/st-portfolio/

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとうございます！
下記ご確認お願いします！

オープニングアニメーション
- [ ] LINEでも伝えた、SPで見た時に動画再生ボタンが出てしまうのはマストで無くしたいです。
その上で可能であればやっぱり毎回動画を再生させたいけど、重くて無理な場合は動画が入っている時と同じ見た目で静止画が入る
→ある程度時間がたってローディングすんだらそのまま動画が動き始める
という感じにしたいです！

- [ ] ページ遷移時に、ぼかしだけだとガタつきがうっすら見えるのが気になるので、ぼかしはいいんだけどその前に一旦ベタ塗り（テクスチャ素材は入った状態のもの）が入ってそのうちにローディング済ませて、その後に今のボカシの動きが入って、ぼかしが徐々になくなりコンテンツガくっきり見えるという感じにしたいなと思ってる、！
ベタ塗りの色は、背景色に合わせる感じで（アバウトは黒、制作一覧詳細はベージュ）やるのが一番自然かなあと思っている。

**Comment by naoki-00-ito** [comment]
修正は #122 で行うのでclose
