### ISSUE TITLE
やはり一覧へ戻るボタンを追加したいので、余白感などfigma参照していただいて追加いただければありがたいです、、

### ISSUE THREAD

**Issue by naoki-00-ito** [INxST/st-portfolio#163]

**Comment by taiki0521** [comment]
@naoki-00-ito 
ご対応いただきありがとう！！
このページだけなんか一覧を見るがおかしくなってるかも？？？ご確認いただければ助かります！

https://inxst.github.io/st-portfolio/works/misia-forest/

**Comment by naoki-00-ito** [comment]
挿入位置が誤っているので修正する
（正しくは`NextWork`の前)

https://github.com/INxST/st-portfolio/blob/main/src/pages/works/misia-forest.astro#L144

**Comment by naoki-00-ito** [comment]
@taiki0521 
https://inxst.github.io/st-portfolio/works/misia-forest/
の一覧へ戻るの位置修正しました！
