### ISSUE TITLE
TOP（他共通パーツ）-フィードバック

### ISSUE THREAD

**Issue by taiki0521** [INxST/st-portfolio#24]
https://inxst.github.io/st-portfolio/

**Comment by taiki0521** [comment]
@naoki-00-ito 
いったんPCのみ。ざっとみた感じでのものなのでまた何かあったら追記していくかもです！


-  FV月の動き、スクロール固定で月が影にかかる形になっているけど、そこまでしっかり見せる感じでなくていいかも。スクロール自体は進むけどそれに応じて動いている感じ。（最後のキラッと左上でるのめっちゃいいからそこまで残したい、、）
そうすれば、[このサイト](https://seitaroyamazaki.com/)みたいな感じでいったん下の要素が出てくるまでの「SCROLL」の画面なくてもシームレスに動き入りながら私についてのコンテンツが出る感じになるかなあ

- 月の動き、影の入り方が少し不自然かも！！多分実際の月の満ち欠けって円が入ってくるわけではなくて円にそって欠けていく感じだからなんだろうなあ。[これもそうだもんねえ](https://x.com/_rnbsn/status/1796417132319887381?s=46&t=fynGp4vGWgAk7O7FyMG1mg)

- アバウトのh2見出し、最後もう少し早く上に上がってもいいかも。もうちょい最後の画像とタイミング近める

- 私たちについてと、制作実績のh2見出し、フェードインアウトの動きつけたいなあ！色々あるとは思うけど、今のところ[このサイト](https://unou.jp/)みたいなぼかしがかかってる感じが印象近いかも

- 制作実績一覧への遷移もアニメーション入れたいねえ、特に「ALL WORKS」のところが特徴的ではあるから[このサイト](https://www.kei-collection.com/about)のページ読み込み時のh1の動きとか入れたら面白いかも

- 制作実績箇所のホバーで画像が大きくなるやつ、いったん閉じなくて良いです！ずっと何かしらはホバーしている感じがいい。[このサイト](https://showkoclub.jp/)もそこらへんシームレスになってる

- フッターとヘッダーの現在地表示したいです！（figmaのデザイン参考に）

- ヘッダーとかメニュー内で使用している縦書き文字のホバー時のアニメーションが今だとただ横移動に見えるから、もう少し斜めからの動きを見せたい。（横書きの文字は良さげだからこのくらいの斜めから入ってる感欲しい）

- menuホバー時の色反転をもっと滑らかに

- アバウトページ側も共通でフッターの出方を[このサイト](https://anaiwood.com/en)みたいな感じで、その上の要素残して、下からなんか出てくるような感じにしたい

- 和文のsemiboldちょっと太すぎる？？特に黒文字で書いている時がぶっといからfont-weight:500;でいいかも。regularは多分400だもんね。ちょっとmacかwindowsかによるかもだけど、いったん500に変更いただければありがたいです！

**Comment by taiki0521** [comment]
私たちについて部分のセピアからカラーへの色の変わり方、下記サイトのスクロールに応じて黄色いマスクが外れるような形で下から上にセピアからカラーにと言うイメージが近いです！
https://kiiro-d.com/

**Comment by naoki-00-ito** [comment]
- [ ] FV月の動き、スクロール固定で月が影にかかる形になっているけど、そこまでしっかり見せる感じでなくていいかも。スクロール自体は進むけどそれに応じて動いている感じ。（最後のキラッと左上でるのめっちゃいいからそこまで残したい、、）
そうすれば、[このサイト](https://seitaroyamazaki.com/)みたいな感じでいったん下の要素が出てくるまでの「SCROLL」の画面なくてもシームレスに動き入りながら私についてのコンテンツが出る感じになるかなあ

- [ ] 月の動き、影の入り方が少し不自然かも！！多分実際の月の満ち欠けって円が入ってくるわけではなくて円にそって欠けていく感じだからなんだろうなあ。[これもそうだもんねえ](https://x.com/_rnbsn/status/1796417132319887381?s=46&t=fynGp4vGWgAk7O7FyMG1mg)

- [ ] アバウトのh2見出し、最後もう少し早く上に上がってもいいかも。もうちょい最後の画像とタイミング近める

- [ ] 私たちについてと、制作実績のh2見出し、フェードインアウトの動きつけたいなあ！色々あるとは思うけど、今のところ[このサイト](https://unou.jp/)みたいなぼかしがかかってる感じが印象近いかも

- [ ] 制作実績一覧への遷移もアニメーション入れたいねえ、特に「ALL WORKS」のところが特徴的ではあるから[このサイト](https://www.kei-collection.com/about)のページ読み込み時のh1の動きとか入れたら面白いかも

- [ ] 制作実績箇所のホバーで画像が大きくなるやつ、いったん閉じなくて良いです！ずっと何かしらはホバーしている感じがいい。[このサイト](https://showkoclub.jp/)もそこらへんシームレスになってる

- [ ] フッターとヘッダーの現在地表示したいです！（figmaのデザイン参考に）

- [ ] ヘッダーとかメニュー内で使用している縦書き文字のホバー時のアニメーションが今だとただ横移動に見えるから、もう少し斜めからの動きを見せたい。（横書きの文字は良さげだからこのくらいの斜めから入ってる感欲しい）

- [ ] menuホバー時の色反転をもっと滑らかに

- [ ] アバウトページ側も共通でフッターの出方を[このサイト](https://anaiwood.com/en)みたいな感じで、その上の要素残して、下からなんか出てくるような感じにしたい

- [ ] 和文のsemiboldちょっと太すぎる？？特に黒文字で書いている時がぶっといからfont-weight:500;でいいかも。regularは多分400だもんね。ちょっとmacかwindowsかによるかもだけど、いったん500に変更いただければありがたいです！

**Comment by naoki-00-ito** [comment]
- [ ] 画像・背景動画の差し替えも合わせて対応

**Comment by naoki-00-ito** [comment]
@taiki0521 
> フッターとヘッダーの現在地表示したいです！（figmaのデザイン参考に）

上記、検証用のURLに`st-portfolio`というパスを挟んでいる影響で動かないです...
(ローカルとルートパスにアップしたときには動くはず...)

<img width="663" alt="image" src="https://github.com/user-attachments/assets/ecc414f2-730e-430b-9bff-9c7d6244d70b">

**Comment by naoki-00-ito** [comment]
@taiki0521 
https://github.com/INxST/st-portfolio/issues/24#issuecomment-2254099560
チェック入れてるものは調整しました！
アニメーション系と、[ヘッダー・フッターのカレント表示](https://github.com/INxST/st-portfolio/issues/24#issuecomment-2254406252)は未対応
https://inxst.github.io/st-portfolio/

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとうございます！！

>  私たちについて部分のセピアからカラーへの色の変わり方、下記サイトのスクロールに応じて黄色いマスクが外れるような形で下から上にセピアからカラーにと言うイメージが近いです！
こちら下記2点ご確認いただきたいです！
- セピアのマスクが取れるアニメーションが、セピアは普通にフェードインでとれて、カラフルになった後に明るさだけが下から上にアニメーションで取れるようになってる？？　セピアも込みで下から上にアニメーションで取れるようにお願いします！
- このアニメーションの発火のタイミングが、一つが中央超えたらセピアからカラフルになるのに連動して全部なってしまっているので、判定を一つ一つに持たせて、それぞれ中央位置くらいを超えたらカラフルになる感じがいいです！

- ボタンもホバー時のアニメーションを添付のような感じで塗りが追加される動きをお願いします！中央から広がっていくようなイメージ。
ちょっと変になりそうだったら、ボタンもテキストリンクと同様にテキストの部分だけ動く感じでもいいかも、、
<img width="440" alt="image" src="https://github.com/user-attachments/assets/fbfddc63-b5c8-4403-8e80-f8e0f0592db9">

**Comment by naoki-00-ito** [comment]
@taiki0521 
https://github.com/INxST/st-portfolio/issues/24#issuecomment-2258729890
と

> FV月の動き、スクロール固定で月が影にかかる形になっているけど、そこまでしっかり見せる感じでなくていいかも。スクロール自体は進むけどそれに応じて動いている感じ。（最後のキラッと左上でるのめっちゃいいからそこまで残したい、、）
そうすれば、このサイトみたいな感じでいったん下の要素が出てくるまでの「SCROLL」の画面なくてもシームレスに動き入りながら私についてのコンテンツが出る感じになるかなあ

調整してみたけどどうだろう？
画像の色がカラーに戻るところについては、CSSで画像自体をグレースケールにしているんだけど、
このグレースケールを戻す方向を下から上にできないらしく、少しタイミングがずれているように見えるかも...
微妙だったら対策考えるので教えてー

https://inxst.github.io/st-portfolio/

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとう！！
- 添付の画像以外の発火のタイミング（カラーに戻るアニメーションが始まるタイミング）が少し早い印象。結構画面下の方で発生するからもう少し真ん中くらいで発生させたいんだけど、これ結構見ているデバイスに左右されちゃう感じかな、、、？

逆に添付の画像はもう少し早いタイミングでいいかなとおもている（macデスクトップ環境だとこの画像だけかなり画面上にいかないとアニメーションかからない）
<img width="786" alt="image" src="https://github.com/user-attachments/assets/d3806536-e1e0-4ce8-b542-6adbdd58b784">


- 立体感出すために、写真のスクロールで進むスピードを写真ごとに変化してもらっていると思うんだけど添付の最初に出てくる2枚がおなじスピードな感じなので、この二つのスピード感を分けたいです！
 
<img width="1986" alt="image" src="https://github.com/user-attachments/assets/4cb0e51f-483b-4fd8-a9b2-24df237945e1">


- あとLINEでも伝えた部分も再度こちらでも記載します。FVの部分、このサイトみたいな感じでFVのセクションを少し残すことってできる？？今だと普通にスクロールで下のセクションがでてるけど、少しFVにかぶさるようなイメージ
https://iwatetown-sdgs.jp/
<img width="2240" alt="image" src="https://github.com/user-attachments/assets/c391397d-6ff0-4f57-95de-150976ab8937">

**Comment by taiki0521** [comment]
@naoki-00-ito 
フッターの「GETINCONTACT」だけど、
添付のように、GET IN CONTACTと単語ごとにスペース開けるのと、次のGET IN CONTACTの文字と文字との距離が今広いから大体添付画像くらい（これだと72pxの余白）にしてほしいです！


あとここの文字を、仮にSVGにしても同様のアニメーションって可能かな？？（フォントファミリーの関係でできればsvgにしたい気持ちがある）

<img width="1570" alt="image" src="https://github.com/user-attachments/assets/ba97a0ba-4bdd-4c83-a25d-4034c15e5bf1">

**Comment by naoki-00-ito** [comment]
@taiki0521 
- hero, footerの重なりエフェクト
- 画像パララックスのタイミング
- 見出しのfadein
- GET IN CONTACTの余白

上記調整したのでご確認お願いします！

https://inxst.github.io/st-portfolio/

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとう！！

▼対応いただいた箇所へのFB
- [ ] アバウト箇所のスピード感が全体的に少し早いので気持ちゆっくりしてほしいのと、画像同士のスピード感添付のようなイメージで調整いただければありがたいです！！（ちょっともしかしたらまたスピード調整していただくかも、、）
<img width="500" alt="image" src="https://github.com/user-attachments/assets/07a1a48d-55ff-47c8-acb7-4b95201ed372">


- [ ] FVの重なりエフェクトの際、[このサイト](https://seitaroyamazaki.com/)とかもそうだけど、確か前やってくれていたやつ残っている側が少し暗くなる感じになっていたと思うのでそれは適用したいです！




<br>
▼追加でいくつかご確認お願いします！

- [ ] worksのところ、画像上の文字がかなり見づらくなるから[このサイトのヘッダー](https://fas-jp.com/)みたいに、背景色に応じて文字色変わる感じにしたいんだけど行けそう？

- [ ] 上記可能そうであればヘッダーにも適用したい！（文字リストとmenuの文字）

- [ ] あと上記の話にも関係するんだけど、今見ているやつとそうでないやつ（添付で言うとmisiaの森が今見ていて、佐藤製麺所が見てないやつ）の色や不透明度を変えたくて、上記の指定次第だけど例えば添付だとmix-blend-mode:color-dodge; にしているんだけどこう言う感じのいけそうかな？（主のやつより目立たない感じにしたいからシンプルに不透明度下げるでもいい） 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/6b913c5f-5782-46cb-a22e-fbf5b5a485b2">



- [ ]    [この課題](https://github.com/INxST/st-portfolio/issues/26#issuecomment-2258742358)の指摘と被るかもだけど、スクロールでマウスストーカーが流れていっちゃうのが気になる！[こんな感じ](https://www.rakuten.design/)でマウスにずっと着いていてほしい


- [ ]   worksのh2が内側によっている？？一応デザイン上だと、添付のところがイコールの想定だった
<img width="500" alt="image" src="https://github.com/user-attachments/assets/81f7d320-8377-434c-857c-6ef73f58f9ea">



- [ ]   前にラインで少し話した、トップのワークス部分の添付の要素が切り替わるやつなんだけど行けそう、、？？あまりにも構造崩さないといけないとかでなければ全然追っての対応していただくと言う形でもありがたい、、、
<img width="500" alt="image" src="https://github.com/user-attachments/assets/5c004cf8-12eb-4e90-956d-0c3315427646">

**Comment by naoki-00-ito** [comment]
表示モード切り替え、同一セッションでは切り替え状態を維持

**Comment by naoki-00-ito** [comment]
@taiki0521 
ページ遷移とローディングは #104 で対応進めます！

**Comment by taiki0521** [comment]
@naoki-00-ito 
追加でFBです！
- [ ] sp時に実績のタイトル消えちゃってるので出してほしいです
<img width="482" alt="image" src="https://github.com/user-attachments/assets/2319dac2-5a8f-410f-bd07-f04d889f908b">
- [ ] ボタンホバー時の動きが遅いので、0.6sに変更ください

**Comment by naoki-00-ito** [comment]
修正は #122 で実施するのでclose
