### ISSUE TITLE
アバウト-フィードバック

### ISSUE THREAD

**Issue by taiki0521** [INxST/st-portfolio#25]
https://inxst.github.io/st-portfolio/about/

**Comment by taiki0521** [comment]
@naoki-00-ito 

- 動画が大きくなる箇所、[このサイト](https://www.zaptec.com/)みたいに全画面になっていいかなあ

- コンテンツ幅が1920pxの段階でデザインと異なる？？ちょっと広すぎるかも

- プロフィール画像もトップのアバウト箇所同様に、セピア→色付きにしたい！

**Comment by naoki-00-ito** [comment]
- [ ] 動画が大きくなる箇所、このサイトみたいに全画面になっていいかなあ
- [ ] コンテンツ幅が1920pxの段階でデザインと異なる？？ちょっと広すぎるかも
- [ ] プロフィール画像もトップのアバウト箇所同様に、セピア→色付きにしたい！

**Comment by naoki-00-ito** [comment]
@taiki0521 

> 動画が大きくなる箇所、このサイトみたいに全画面になっていいかなあ
> コンテンツ幅が1920pxの段階でデザインと異なる？？ちょっと広すぎるかも

この2つ調整してみたけどうだろう...

https://inxst.github.io/st-portfolio/about/

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとう！！
良い感じです！！
コンテンツ幅調整していただいた影響で添付のCareerの箇所が幅狭まってしまったので調整お願いします、、！

<img width="1915" alt="image" src="https://github.com/user-attachments/assets/4991618f-42ec-4e11-9eae-0a47d158f88d">

**Comment by taiki0521** [comment]
@naoki-00-ito 
添付のスクロールで画像が大きくなる部分、大きくなり始めるのがブラウザ頭についた時からなんだけど、中央くらいから大きくなり始めることってできる？？
[こんくらいのタイミングのイメージ](https://seitaroyamazaki.com/)

<img width="2240" alt="image" src="https://github.com/user-attachments/assets/76cfcbae-287d-4c02-80be-7e38523d91ae">

**Comment by taiki0521** [comment]
@naoki-00-ito 
- スクロールで大きくなる画像の箇所、スクロール中は画像切り替え止まってしまっているぽいけどこの間も変わらず画像切り替わり続ける形にできればしたいです！
<img width="1946" alt="image" src="https://github.com/user-attachments/assets/67c56ddd-daf8-4382-9d28-d998082ab456">

- あと上記の箇所、画像の拡大縮小の時すごいブルブルしてるから可能であれば滑らかにしたい、、、、（ブラウザとかデバイスに依存するのかなあ、、）

- ごめん、、添付のプロフィール部分の要素ちょっと見直しました。「web design~」とかのところは消しで、「TAIKI SATO」の文字色変更でお願いします！
あと、PC時のみ名前と文章の間の余白を40px相当に変更でお願いします！
<img width="1677" alt="image" src="https://github.com/user-attachments/assets/dc628b9c-9de9-4c74-8ac0-f1fa7ac4ce51">

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとう！！！！めちゃくちゃいい感じです！！！（MV部分の大きくなる感じ躍動感ある動きで最高）

一個これaboutだけの話じゃないと思うんだけど、sp時の左右の余白が少しデザインより狭くて調整できそう？？（これ調整するとなんか問題とかありそうだったら教えてほしいー！）
多分ブラウザ幅によって可変で動く感じだと思うけどもう気持ち左右広めたいです！！

<img width="500" alt="image" src="https://github.com/user-attachments/assets/86dbcb94-5fe4-45d8-a83a-904b899c7505">

**Comment by naoki-00-ito** [comment]
@taiki0521 
左右のpaddingについて、
h1左が40px、それ以外が20pxになっていると思うけど、どう調整するのがイメージ近い？
サイズ可変するけど現状iPhoneSEで左右17.5pxなのを20に近い値にして、h1の左に追加で余白付ける感じが良い？
それとも全て一律で広げちゃって良い？

**Comment by taiki0521** [comment]
> サイズ可変するけど現状iPhoneSEで左右17.5pxなのを20に近い値にして、h1の左に追加で余白付ける感じが良い？
左右の余白全ページこれでお願いします！（ブラウザ幅375pxの段階で20近くくらいあってもいいかなあと思っている）



> h1左が40px、それ以外が20pxになっていると思うけど
h1って現状コーディング上では、左右統一の20pxの余白がついているだけで、左が40px(20+20）になってないかなと思っているんだけどわいの環境があれなのかな？？　今余白着いてなかったら左右のやつを調整するタイミングで合わせて追加お願いします！

**Comment by taiki0521** [comment]
@naoki-00-ito 
- [ ] sp時の画像が大きくなってくる箇所が、大きくなり始めるのがブラウザ上で上の方に行った時から大きくなるけど、これ中央あたりからどんどん大きくなる感じにできる？？？スタート位置を画面中央ちょい上とかにしたいという感じです
（pcは今の位置から大きくなるのでいいです！！）
<img width="545" alt="image" src="https://github.com/user-attachments/assets/7abb3509-ce5f-4c86-b66e-538d90e47c37">

- [ ] sp時のh1は、[制作一覧の方](https://github.com/INxST/st-portfolio/issues/26#issuecomment-2310291413)https://github.com/INxST/st-portfolio/issues/26#issuecomment-2310291413でも指摘したように左側に同様に余白ください

**Comment by naoki-00-ito** [comment]
修正は #122 で実施するのでclose
