### ISSUE TITLE
制作実績一覧-フィードバック

### ISSUE THREAD

**Issue by taiki0521** [INxST/st-portfolio#26]
https://inxst.github.io/st-portfolio/works/

**Comment by taiki0521** [comment]
- このページとか、実績詳細側のページの画像とかスクロールに合わせて[こういうモーション](https://www.s5-studios.com/works/branding/)（もっとゆらめく感じでもいい）を軽く入れられたら素敵やなあと思った！！

- filterの絞り込みでの出入りの動きが少し大袈裟な印象（特に絞り込まれて外された時の動き）。もっと滑らかな感じだと良さげかも。スピードが早めだと言うのもありそう

- h1と1個目のスライダーの余白をもっとあけたい（デザイン参照）。ノートパソコンだと少し縮めたいが、1920時はデザインのくらい開けたいなあと

- 私たちについての横渡の後ろ側がすごい開いちゃってる？？（macデスクトップ環境、ブラウザ幅2400pxくらいかな）

- アバウトページ側も同様だけど、h1のサブテキストの頭の位置が下すぎるかも！ピッタリ数値通りにh1と頭をくっつけると少しサブテキストが頭出て見えるので、デザイン上はサブテキスト側に上余白持たせて目視で同じくらいにしている。
あと、h1とサブテキストの距離も近いので少し余白欲しいです！

**Comment by naoki-00-ito** [comment]
@taiki0521 

- [ ] このページとか、実績詳細側のページの画像とかスクロールに合わせてこういうモーション（もっとゆらめく感じでもいい）を軽く入れられたら素敵やなあと思った！！
- [ ] filterの絞り込みでの出入りの動きが少し大袈裟な印象（特に絞り込まれて外された時の動き）。もっと滑らかな感じだと良さげかも。スピードが早めだと言うのもありそう
- [ ] h1と1個目のスライダーの余白をもっとあけたい（デザイン参照）。ノートパソコンだと少し縮めたいが、1920時はデザインのくらい開けたいなあと
- [ ] 私たちについての横渡の後ろ側がすごい開いちゃってる？？（macデスクトップ環境、ブラウザ幅2400pxくらいかな）
- [ ] アバウトページ側も同様だけど、h1のサブテキストの頭の位置が下すぎるかも！ピッタリ数値通りにh1と頭をくっつけると少しサブテキストが頭出て見えるので、デザイン上はサブテキスト側に上余白持たせて目視で同じくらいにしている。
あと、h1とサブテキストの距離も近いので少し余白欲しいです！

**Comment by naoki-00-ito** [comment]
@taiki0521 
スクロールのモーション以外は反映してみたのでご確認お願いします！
解消していないもの、認識違うものは
https://github.com/INxST/st-portfolio/issues/26#issuecomment-2245948685
のチェック外しておいてほしいです！

**Comment by taiki0521** [comment]
@naoki-00-ito 
ごめん確認遅くなったありがとうございます！！！

上記の中で言うと、filterの絞り込みがまだ少し気になるかも、、
抜ける時も入ってくる時にもある、ちょっと大きくなる動きがなくてもいいのかなあ、と思った！（これ無くすと変になるかな、、？）ご確認お願いします！




▼ちょっとプラスアルファで細かいところFBさせてください！！
○共通
- タグが2行になった際と1行で画像の大きさが異なるから統一して欲しい。ベースを2行として1行の時は単純に余白として残っているでもいいかなと（sp時も下記で指摘しているrow-gapを調整したら3行でも下に逃すでいけるかな、、？）
- 各実績詳細への遷移カードについてる各カテゴリのタグのrow-gapを0.2remに
- 「私たちについて」の文字のデザイン更新お願いします！（下線引かなくなったりとか）

○PC
- 実績詳細のタイトル30px→28pxに
- h1サブテキストのmargin-leftを1→0.8remに

**Comment by taiki0521** [comment]
@naoki-00-ito 
あとごめん合わせて絞り込みの項目をひとまず下記にして欲しいです！
- All
- Art Direction
- Web Design
- Graphic Design
- Fashion Design
- coding

<img width="875" alt="image" src="https://github.com/user-attachments/assets/5d70c2b5-7aff-4336-9ce7-51fadad7fa24">

**Comment by taiki0521** [comment]
@naoki-00-ito 
五月雨にごめん！
結構細かいんだけど、
制作一覧と制作詳細側も、横スクロールの際に、背景色は普通に縦スクロールになっているのが少し気になるかも、、！（背景のテクスチャ入れてるからその要素だけ縦移動してる）

制作詳細がわは全体的に、制作一覧はヘッダーの部分の背景だけ縦スクロールになっているぽい！

**Comment by taiki0521** [comment]
@naoki-00-ito 
あと上記の指摘と被るのかもしれないけど、横スクロール箇所の時にスクロールしているとマウスストーカーが上に流れていっちゃうので調整していただきたいです、、！

**Comment by taiki0521** [comment]
@naoki-00-ito 
macのデスクトップの画面幅の際、制作実績が添付画像の位置でとまり、私たちについてが出てこない、、！

<img width="2240" alt="image" src="https://github.com/user-attachments/assets/95ae6496-c04d-4d17-9735-c5bc245b4b0c">

**Comment by naoki-00-ito** [comment]
- tagは2行分領域確保
- titleは1行であふれる分は三点リーダーで省略

イメージ

<img width="1299" alt="スクリーンショット 2024-08-15 21 28 54" src="https://github.com/user-attachments/assets/d02ab3ea-1c7b-4def-8317-7b981d1af17a">

**Comment by taiki0521** [comment]
@naoki-00-ito 
可能であれば、sp時に、縦スクロールだけじゃなくて横にスワイプで横に動くようにもしたいのですが、可能かな、、？

**Comment by naoki-00-ito** [comment]
修正は #122 で実施するのでclose
