### ISSUE TITLE
制作実績詳細-FB

### ISSUE THREAD

**Issue by taiki0521** [INxST/st-portfolio#43]
https://inxst.github.io/st-portfolio/works/detail/

**Comment by taiki0521** [comment]
- 添付部分の画像の箇所も、項目内容（Description）箇所も、想定としては、1920px時に上下に（ヘッダーも含む）120pxずつ余白が開いて、レスポンシブに合わせて縮んでいくような想定だった！
絶対にそういう指定がいいというわけではないんだけど、今だと横渡の下の部分が揃ってないのと、項目内容の箇所が画像部分より高さ出てしまっているのが気になる！
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/9643de29-1c76-4502-9989-95a691995e10">

- 上記の指摘とも少し被るけど、項目内容のところが項目下に余白開きすぎなので調整して欲しいです！で、できる限りここの高さを右隣の画像より出したくないんだけど文字量に依存はしちゃいそうだから、一旦Figma内に入れるであろう文字要素が入ったボードを用意したので（pcの実績詳細デザインの下に置いてある）、そちらも入れた上で調整いただければありがたいです、、！！

- MV部分と、Overview後の画像の横幅を変えるかも（また用意したら共有します）。あとこの二つの画像箇所に（全高さ画像）[このサイト](https://umiral.jp/)みたいな感じでパララックス入れたいです！

-項目内容（Description）箇所の後に実績によって数は変動するけど色々画像入れていく（逆にその前の箇所は大体どの実績も同様にコンテンツが入る）想定なんだけど、ここ動画とyoutube埋め込みも入れれるようにして欲しいです！（どっちの場合もありそう）

**Comment by naoki-00-ito** [comment]
- [ ] 添付部分の画像の箇所も、項目内容（Description）箇所も、想定としては、1920px時に上下に（ヘッダーも含む）120pxずつ余白が開いて、レスポンシブに合わせて縮んでいくような想定だった！絶対にそういう指定がいいというわけではないんだけど、今だと横渡の下の部分が揃ってないのと、項目内容の箇所が画像部分より高さ出てしまっているのが気になる！
- [ ] 上記の指摘とも少し被るけど、項目内容のところが項目下に余白開きすぎなので調整して欲しいです！で、できる限りここの高さを右隣の画像より出したくないんだけど文字量に依存はしちゃいそうだから、一旦Figma内に入れるであろう文字要素が入ったボードを用意したので（pcの実績詳細デザインの下に置いてある）、そちらも入れた上で調整いただければありがたいです、、！！
- [ ] MV部分と、Overview後の画像の横幅を変えるかも（また用意したら共有します）。あとこの二つの画像箇所に（全高さ画像）このサイトみたいな感じでパララックス入れたいです！
- [ ] 項目内容（Description）箇所の後に実績によって数は変動するけど色々画像入れていく（逆にその前の箇所は大体どの実績も同様にコンテンツが入る）想定なんだけど、ここ動画とyoutube埋め込みも入れれるようにして欲しいです！（どっちの場合もありそう）

**Comment by naoki-00-ito** [comment]
@taiki0521 
https://github.com/INxST/st-portfolio/issues/43#issuecomment-2254098192
のパララックス以外は修正しました🤯
- https://inxst.github.io/st-portfolio/works/textile-manufacturer-site/
- https://inxst.github.io/st-portfolio/works/detail/

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとうございます！！
あとごめん、、、前にいらないっていったんだけど、添付のパターンが存在しそうだから、sp時に画像の2分割も一応用意いただいてもいいですか、、、

<img width="1485" alt="image" src="https://github.com/user-attachments/assets/0962c30e-a93f-4882-8b25-959be378d2f9">

**Comment by taiki0521** [comment]
@naoki-00-ito 
制作実績詳細内に入るパターンで下記二つ追加してほしいです！
- 動画の[自動再生&ループパターン](https://shiftbrain.com/work/layerx-branding/)と、[再生ボタン押してから流れるパターン](https://taikisato.com/html/design/other01.html)（音声あり）
- 添付のようにpcとspで画像が切り替わるタイプ
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/4b0da3dc-7b8d-43a6-9d29-a7ca3761e981">

**Comment by naoki-00-ito** [comment]
@taiki0521 

> @naoki-00-ito ありがとうございます！！ あとごめん、、、前にいらないっていったんだけど、添付のパターンが存在しそうだから、sp時に画像の2分割も一応用意いただいてもいいですか、、、
> 
> <img alt="image" width="1485" src="https://private-user-images.githubusercontent.com/174192721/353539764-0962c30e-a93f-4882-8b25-959be378d2f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTYxMDgsIm5iZiI6MTcyMzU1NTgwOCwicGF0aCI6Ii8xNzQxOTI3MjEvMzUzNTM5NzY0LTA5NjJjMzBlLWE5M2YtNDg4Mi04YjI1LTk1OWJlMzc4ZDJmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMzMwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTI2OWQ2MTUxYzY3YmM5MmFlZTE4MmVjN2RkZDVkNTZjOTQzOWE3ZWMxYjA0M2ZjYjUwZTlkMzZkZWM5MDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-q55GqClwNryp8ogg-5E_W1yPBbNPgFX2ZSCMyP2Elw">

SP2分割作成して下記ページに利用してます！

https://inxst.github.io/st-portfolio/works/keio-fashion-creator/

**Comment by naoki-00-ito** [comment]
@taiki0521 

> @naoki-00-ito 制作実績詳細内に入るパターンで下記二つ追加してほしいです！
> 
> * 動画の[自動再生&ループパターン](https://shiftbrain.com/work/layerx-branding/)と、[再生ボタン押してから流れるパターン](https://taikisato.com/html/design/other01.html)（音声あり）
> * 添付のようにpcとspで画像が切り替わるタイプ（基本的にはpc,sp共通想定）
> 
> <img alt="image" width="1156" src="https://private-user-images.githubusercontent.com/174192721/357267028-4b0da3dc-7b8d-43a6-9d29-a7ca3761e981.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTYxMDgsIm5iZiI6MTcyMzU1NTgwOCwicGF0aCI6Ii8xNzQxOTI3MjEvMzU3MjY3MDI4LTRiMGRhM2RjLTdiOGQtNDNhNi05ZDI5LWE3Y2EzNzYxZTk4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMzMwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTAwMjViZjJkMTkxYmRlYmEwNzIzMWMyNzQwZTQ4NmFhY2QxOTE4ZDgwMmY2OTkwMDM3Yjg5NTIyZDI4MTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cqfe9O_ZCBfZ6O3BgZpTK4k3mqtdsR56KuEKldK3zwU">


### 自動再生・ループ
https://inxst.github.io/st-portfolio/works/5days/

#### 音ありボタンで再生
https://inxst.github.io/st-portfolio/works/misia-forest/

**Comment by taiki0521** [comment]
@naoki-00-ito 
ありがとう！！いくつかFBです！！

- 最初ページインした時、アニメーションをつけている影響かもだけど、MV部分は最初から表示されるようにしてほしい！！
<img width="2240" alt="image" src="https://github.com/user-attachments/assets/6a0ba17a-da15-4891-a5b4-9e0474d954b7">

- 上記添付のタイトル部分だけどmax-width決めて改行される形がいいかなあ、、改行ない形だと画像の始まり部分がずれちゃうと思うので、一旦デザイン上だと640pxをmaxで作ってた！→ページ終わりの横渡りの部分も同様

- h1のフォントウェイトを500にしてほしい


▼sp時
- h1とprivateworksの文字の距離感が結構空いているのでもう少しデザインくらいの距離感にしたい！
- 横渡の文字が右寄せになっているから左寄せに
- また横渡の要素の上の余白はもっと広げたい（デザイン上だと104px）

**Comment by taiki0521** [comment]
@naoki-00-ito 
加えてもう一点お願いします！
添付の箇所の項目内容の内容のフォントサイズは1920px時で16pxでお願いします！
（Overviewの箇所の文章は18pxで大丈夫）

<img width="1598" alt="image" src="https://github.com/user-attachments/assets/162fe661-aa7f-4be5-a8c0-3f4d0c91f0e3">

**Comment by taiki0521** [comment]
@naoki-00-ito 
- [ ] safariで見たときに制作実績詳細がかなり死んでいるので（横渡の部分）、確認して欲しいです！！（他にもメニュー周りの余白感が変だったりした）
<img width="2240" alt="image" src="https://github.com/user-attachments/assets/a770a286-4442-481a-8d87-8d0843ed0783">

**Comment by naoki-00-ito** [comment]
修正は #122 で実施するのでclose
